In [ ]:
!pip install gym

import gym

import numpy as np
import matplotlib.pyplot as plt
import random
import time

In [ ]:
env = gym.make( "FrozenLake-v1", map_name="8x8")

In [29]:
MAP = [[ env.desc[h,w].decode('UTF-8') for w in range(env.desc.shape[1])] for h in range( env.desc.shape[0])]
STATES = [[  w + h * env.desc.shape[1] for w in range(env.desc.shape[1])] for h in range( env.desc.shape[0])]

def display_env( M, S, s):
    RED = "\033[2;31;43m"
    BLACK = "\033[0m"
    
    H = len( M)
    W = len( M[0])

    assert H == len(S) and W == len( S[0]), "Sizes does not agrees"

    RENDER = ""
    for h in range( H):
        for w in range( W):  
            if s == S[h][w]:
                RENDER += RED + M[h][w] + BLACK
            else:
                RENDER += M[h][w]
        RENDER += "\n"
    print( RENDER ) 

s = random.randint( 0, len( MAP) * len( MAP[0]) - 1)
display_env( MAP, STATES, s)

SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG



In [20]:
# Init Q-table:
N_action = env.action_space.n 
N_state = env.observation_space.n

Qtable = np.zeros( (N_state, N_action) )

# Init Parameters:
N_episode = 25000
N_steps = 100

LR = 0.001
gamma = 0.99

# Epsilon Grredy Strategy:
epsilon = 1.0
epsilon_decay = 0.001

max_epsilon = 1.0
min_epsilon = 0.1

In [36]:
from tqdm import tqdm

rewards = []

for episode in tqdm( range( N_episode)):
    state = env.reset()

    done = False
    ereward = 0

    for step in range( N_steps):
        r = random.uniform( 0, 1)
        if r > epsilon:
            action = np.argmax( Qtable[ state, :])
        else:
            action = env.action_space.sample()
        
        new_state, reward, done, info = env.step( action)

        Qtable[ state, action] = ( 1 - LR) * Qtable[ state, action] + \
                                  LR * ( reward + gamma * np.max( Qtable[ new_state, :]) )
        
        state = new_state
        ereward += reward

        if done:
            break

    explor_rate = min_epsilon + \
                  ( max_epsilon - min_epsilon) * np.exp( - episode * epsilon_decay )
    rewards.append( ereward)


print( Qtable)

100%|██████████| 25000/25000 [00:46<00:00, 540.69it/s]

[[9.86748596e-02 9.97918201e-02 9.94962927e-02 1.20845050e-01]
 [9.23890189e-02 9.61295648e-02 1.25333676e-01 9.57959499e-02]
 [9.16942248e-02 9.58851456e-02 1.32916060e-01 9.53113613e-02]
 [9.02395140e-02 9.15984535e-02 1.42676252e-01 9.66736823e-02]
 [8.73322378e-02 9.78267425e-02 1.54541113e-01 9.77932333e-02]
 [1.06095828e-01 1.09505460e-01 1.72302330e-01 1.08429095e-01]
 [9.63989770e-02 9.34939448e-02 1.83027675e-01 9.35425497e-02]
 [1.79877240e-01 1.79696683e-01 1.89984711e-01 1.77304492e-01]
 [4.08163843e-02 4.35961264e-02 4.11081200e-02 1.18012801e-01]
 [6.30352372e-02 6.32733114e-02 6.62712547e-02 1.22084958e-01]
 [6.25579323e-02 6.56842475e-02 7.06399931e-02 1.28627345e-01]
 [4.73864441e-02 4.93678709e-02 4.94495802e-02 1.36249740e-01]
 [7.08814115e-02 7.14941839e-02 1.43402994e-01 8.07730490e-02]
 [1.01568185e-01 1.03903276e-01 1.68194711e-01 1.08936739e-01]
 [1.12695242e-01 1.82749573e-01 1.19455952e-01 1.13013442e-01]
 [1.81729172e-01 1.82802439e-01 1.95539676e-01 1.771817

In [34]:
for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(N_steps):
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax( Qtable[ state, :])
        new_state, reward, done, info = env.step(action)

        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            display_env( MAP, STATES, new_state )
            
            # We print the number of step it took.
            print("Number of steps", step)
            break
        state = new_state
env.close()

****************************************************
EPISODE  0
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG

Number of steps 18
****************************************************
EPISODE  1
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG

Number of steps 99
****************************************************
EPISODE  2
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG

Number of steps 26
****************************************************
EPISODE  3
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG

Number of steps 49
****************************************************
EPISODE  4
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG

Number of steps 85
